/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sensors */
        get: operations["list_sensors_v1_sensors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sensors/{sensor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sensor */
        get: operations["get_sensor_v1_sensors__sensor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/aois": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Aois */
        get: operations["list_aois_v1_aois_get"];
        put?: never;
        /** Create Aoi */
        post: operations["create_aoi_v1_aois_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/aois/{aoi_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Aoi */
        get: operations["get_aoi_v1_aois__aoi_id__get"];
        put?: never;
        post?: never;
        /** Delete Aoi */
        delete: operations["delete_aoi_v1_aois__aoi_id__delete"];
        options?: never;
        head?: never;
        /** Update Aoi */
        patch: operations["update_aoi_v1_aois__aoi_id__patch"];
        trace?: never;
    };
    "/v1/aois/{aoi_id}/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aoi Scenes */
        get: operations["aoi_scenes_v1_aois__aoi_id__scenes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/aois/{aoi_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aoi Metrics */
        get: operations["aoi_metrics_v1_aois__aoi_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scenes/{scene_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scene */
        get: operations["get_scene_v1_scenes__scene_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tiles/scenes/{scene_id}/tilejson.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tilejson */
        get: operations["tilejson_v1_tiles_scenes__scene_id__tilejson_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tiles/scenes/{scene_id}/{z}/{x}/{y}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tile Png */
        get: operations["tile_png_v1_tiles_scenes__scene_id___z___x___y__png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AoiCreate */
        AoiCreate: {
            /** Name */
            name: string;
            /** Geojson */
            geojson: {
                [key: string]: unknown;
            };
            /**
             * Is Public
             * @default false
             */
            is_public: boolean;
        };
        /** AoiDetail */
        AoiDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Is Public */
            is_public: boolean;
            /** Area M2 */
            area_m2: number;
            bbox: components["schemas"]["Bbox"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Geom */
            geom: {
                [key: string]: unknown;
            };
            /** Sensor State */
            sensor_state: components["schemas"]["SensorStateOut"][];
        };
        /** AoiOut */
        AoiOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Is Public */
            is_public: boolean;
            /** Area M2 */
            area_m2: number;
            bbox: components["schemas"]["Bbox"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AoiUpdate */
        AoiUpdate: {
            /** Name */
            name?: string | null;
            /** Is Public */
            is_public?: boolean | null;
        };
        /** BandOut */
        BandOut: {
            /** Name */
            name: string;
            /** Asset Key */
            asset_key: string;
            /** Kind */
            kind: string;
            /** Resolution M */
            resolution_m: number | null;
            /** Scale */
            scale: number;
            /** Dn Offset */
            dn_offset: number;
        };
        /** Bbox */
        Bbox: {
            /** Minx */
            minx: number;
            /** Miny */
            miny: number;
            /** Maxx */
            maxx: number;
            /** Maxy */
            maxy: number;
        };
        /** CollectionOut */
        CollectionOut: {
            /** Id */
            id: string;
            /** Catalog */
            catalog: string;
            /** Stac Url */
            stac_url: string;
            /** Processing Level */
            processing_level: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MetricPoint */
        MetricPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Acquired At
             * Format: date-time
             */
            acquired_at: string;
            /** Scene Id */
            scene_id: number;
            /** Value */
            value: number;
            /** Valid Pixel Pct */
            valid_pixel_pct: number;
        };
        /** MetricSeries */
        MetricSeries: {
            /** Metric Name */
            metric_name: string;
            /** Sensor Id */
            sensor_id: string;
            /** Unit */
            unit: string;
            /** Points */
            points: components["schemas"]["MetricPoint"][];
        };
        /** MetricsResponse */
        MetricsResponse: {
            /**
             * Aoi Id
             * Format: uuid
             */
            aoi_id: string;
            /** Series */
            series: components["schemas"]["MetricSeries"][];
        };
        /** Page[AoiOut] */
        Page_AoiOut_: {
            /** Items */
            items: components["schemas"]["AoiOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[SceneSummary] */
        Page_SceneSummary_: {
            /** Items */
            items: components["schemas"]["SceneSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[SensorOut] */
        Page_SensorOut_: {
            /** Items */
            items: components["schemas"]["SensorOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** SceneDetail */
        SceneDetail: {
            /** Id */
            id: number;
            /** Scene Key */
            scene_key: string;
            /** Sensor Id */
            sensor_id: string;
            /** Collection Id */
            collection_id: string;
            /**
             * Acquired At
             * Format: date-time
             */
            acquired_at: string;
            /** Cloud Cover */
            cloud_cover: number | null;
            /** Epsg */
            epsg: number | null;
            /** Footprint */
            footprint: {
                [key: string]: unknown;
            };
            bbox: components["schemas"]["Bbox"];
            /** Assets */
            assets: {
                [key: string]: unknown;
            };
            /** Properties */
            properties: {
                [key: string]: unknown;
            };
        };
        /** SceneSummary */
        SceneSummary: {
            /** Id */
            id: number;
            /** Scene Key */
            scene_key: string;
            /** Sensor Id */
            sensor_id: string;
            /** Collection Id */
            collection_id: string;
            /**
             * Acquired At
             * Format: date-time
             */
            acquired_at: string;
            /** Cloud Cover */
            cloud_cover: number | null;
            /** Coverage */
            coverage: number;
        };
        /** SensorDetail */
        SensorDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Provider */
            provider: string;
            /** Resolution M */
            resolution_m: number | null;
            /** Revisit Days */
            revisit_days: number | null;
            /** Enabled */
            enabled: boolean;
            /** License Text */
            license_text: string;
            /** Collections */
            collections: components["schemas"]["CollectionOut"][];
            /** Bands */
            bands: components["schemas"]["BandOut"][];
        };
        /** SensorOut */
        SensorOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Provider */
            provider: string;
            /** Resolution M */
            resolution_m: number | null;
            /** Revisit Days */
            revisit_days: number | null;
            /** Enabled */
            enabled: boolean;
        };
        /** SensorStateOut */
        SensorStateOut: {
            /** Sensor Id */
            sensor_id: string;
            /** Last Checked At */
            last_checked_at: string | null;
            /** Last Scene At */
            last_scene_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sensors_v1_sensors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SensorOut_"];
                };
            };
        };
    };
    get_sensor_v1_sensors__sensor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_aois_v1_aois_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AoiOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_aoi_v1_aois_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AoiCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AoiOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_aoi_v1_aois__aoi_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aoi_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AoiDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_aoi_v1_aois__aoi_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aoi_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_aoi_v1_aois__aoi_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aoi_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AoiUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AoiOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aoi_scenes_v1_aois__aoi_id__scenes_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                sensor?: string | null;
            };
            header?: never;
            path: {
                aoi_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SceneSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aoi_metrics_v1_aois__aoi_id__metrics_get: {
        parameters: {
            query?: {
                metric?: string | null;
                sensor?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path: {
                aoi_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scene_v1_scenes__scene_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scene_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tilejson_v1_tiles_scenes__scene_id__tilejson_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scene_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tile_png_v1_tiles_scenes__scene_id___z___x___y__png_get: {
        parameters: {
            query?: {
                /** @description comma-separated band names */
                assets?: string | null;
                /** @description reflectance display max */
                stretch?: number;
            };
            header?: never;
            path: {
                scene_id: number;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
